apiVersion: v1
kind: Service
metadata:
  name: student-app-api
  namespace: reactjava
spec:
  selector:
    app: student-app-api
  ports:
    - port: 9002
      protocol: TCP
      targetPort: 8080
      nodePort: 30061
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app-api
  namespace: reactjava
spec:
  selector:
    matchLabels:
      app: student-app-api
  replicas: 1
  template:
    metadata:
      labels:
        app: student-app-api
    spec:
      containers:
        - name: student-app-api
          image: nirajsonawane/student-app-api:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always

